environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 2015"
      CONFIG: Release

build_script:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" -DBOOST_INCLUDEDIR:PATH=C:/Libraries/boost_1_58_0 -DBOOST_LIBRARYDIR:PATH=C:/Libraries/boost_1_58_0/lib32-msvc-14.0 ..
  - cmake --build . --config %CONFIG%
